version: "3.9"
services:
  frontend:
    image: nginx:latest
#    build:
#      context: ./frontend
#      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
#      - ./frontend:/app
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      POSTGRES_USER: kratz_5
      POSTGRES_PASSWORD: 676568
      POSTGRES_DB: my_db_energy
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kratz_5
      POSTGRES_PASSWORD: 676568
      POSTGRES_DB: my_db_energy
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/html  # Assuming your React build is in frontend/build
    depends_on:
    - frontend
    - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
volumes:
  postgres_data: